name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Cafe_Management_System/api-gateway/Dockerfile --tag api-gateway:$(date +%s)

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Cafe_Management_System/customer-services/Dockerfile --tag customer-services:$(date +%s)

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Cafe_Management_System/inventory-services/Dockerfile --tag inventory-services:$(date +%s)

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Cafe_Management_System/menu-services/Dockerfile --tag menu-services:$(date +%s)

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Cafe_Management_System/order-services/Dockerfile --tag order-services:$(date +%s)

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Cafe_Management_System/payment-services/Dockerfile --tag payment-services:$(date +%s)
